name: Docker Image CI

on:
  push:
    branches: ["main", "build"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push WEB Image
        uses: docker/build-push-action@v2
        with:
          context: ./Zaliczenie
          file: ./Zaliczenie/dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/web:latest

      - name: Build and Push API Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Zaliczenie/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/api:latest
